#page title
page_title                                : Scander                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://www.apple.com/gr/ios/app-store/   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.milouk.scander&fbclid=IwAR3A5T6rU34C10IMd8xF4CYxaGPCS9hLjVFum_sgVb5zWgG_bkbTJqJcneU             # Enter Google Play Store URL.
presskit_download_link                    : http://app.scander.gr/login               # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_icon.png                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Scander                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Η νέα εφαρμογή για ανέπαφες παραγγελίες σε χώρους εστίασης.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Emil Baehr
your_link                                 : https://emilbaehr.com
your_city                                 : Copenhagen
email_address                             : scanderapp@gmail.com
facebook_username                         : Scander-110095954023305
instagram_username                        : scanderapp/?hl=el
twitter_username                          :
github_username                           :
youtube_username                          :


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Εύκολο στη χρήση
    description                           : Η μοναδική διεπαφή χρήστη της εφαρμογής προσφέρει μια ευχάριστη εμπειρία στο καταναλωτή.
    fontawesome_icon_name                 : mobile

  - title                                 : Κλήση Σερβιτόρου on Demand
    description                           : Μπορείτε να καλέσετε ανά πάσα στιγμή ένα σερβιτόρο με το πάτημα ενός κουμπιού είτε για να πληρώσετε είτε για να σας βοηθήσει ενώ παράλληλα ενημερώνεστε για το ποιος θα σας εξυπηρετήσει.
    fontawesome_icon_name                 : bell

  - title                                 : Παραγγελία χωρίς αναμονές
    description                           : Παραγγείλτε αυτόματα χωρίς να περιμένετε για κάποιον να σας εξυπηρετήσει μέσα από την εφαρμογή.
    fontawesome_icon_name                 : clock

  - title                                 : Ανακαλύψτε νέα μαγαζιά
    description                           : Μέσα από την εφαρμογή μπορείτε να ανακαλύψετε νέα μαγαζιά για ποτό ή φαγητό.
    fontawesome_icon_name                 : search

  - title                                 : Πάντα ενημερωμένοι κατάλογοι
    description                           : Η εφαρμογή διατηρεί πλήρως ανανεωμένους καταλόγους μαγαζιών χωρίς να χρειάζεται να ανησυχείτε για το αν κάποιο προϊόν είναι διαθέσιμο ή όχι.
    fontawesome_icon_name                 : utensils

  - title                                 : Ιστορικό Παραγγελιών
    description                           : Η εφαρμογή παρέχει την δυνατότητα να διατηρείτε το ιστορικό των παραγγελιών σας.
    fontawesome_icon_name                 : history

  - title                                 : Μείωση λάθους παραγγελιών
    description                           : Χρησιμοποιώντας την εφαρμογή Scander μειώνεται το ενδεχόμενο λάθος σε μια παραγγελία.
    fontawesome_icon_name                 : level-down-alt

  - title                                 : Φιλικό προς το περιβάλλον
    description                           : Το Scander με μεγάλη ευθύνη απέναντι στο περιβάλλον συμβάλλει στη μείωση των χάρτινων και πλαστικών καταλόγων.
    fontawesome_icon_name                 : globe-americas

  - title                                 : Αγαπημένα Μέρη
    description                           : Εάν κάποιο μέρος που επισκεφθήκατε σας εντυπωσίασε, μπορείτε να το αποθηκεύσετε στα αγαπημένα σας έτσι ώστε να το επισκεφθείτε ξανά.
    fontawesome_icon_name                 : heart

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.


# Partners Section
partners                                  :

  - title                                 : ΜΟΚΕ
    logo                                  : assets/moke.jpg
    link                                  : https://www.aueb.gr/el/content/10os-diagonismos-epiheirimatikotitas-tis-moke-opa-dilose-ti-symmetohi-soy

  - title                                 : ACEIN
    logo                                  : assets/acein.png
    link                                  : https://acein.aueb.gr/

  - title                                 : AUEB
    logo                                  : assets/aueb.png
    link                                  : https://aueb.gr/


# Global Variables
partners_header                           : Με την υποστήριξη


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"
topbar_title_color_right                  : "#e1ff81"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
